<x-layouts.app>
	<x-slot:toolbar>
		<x-model.trigger.create
			for="create_product"
			model-name="Product"
		/>
	</x-slot:toolbar>
	<livewire:products.index-table
		:$product_type_options
		:$scent_options
	/>
</x-layouts.app>
